# Generated by Django 4.1.7 on 2023-03-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='lang',
            field=models.CharField(default='uz', max_length=2),
        ),
    ]
