# Generated by Django 4.1.7 on 2023-03-28 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapi', '0002_alter_usersmodel_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomodel',
            name='location',
            field=models.TextField(default=datetime.datetime(2023, 3, 28, 4, 35, 7, 603310, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
