# Generated by Django 4.1.7 on 2023-03-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rename_usermodel_usersmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomodel',
            name='bot_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='lang',
            field=models.CharField(max_length=2),
        ),
    ]
