# Generated by Django 4.1.7 on 2023-03-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapi', '0003_infomodel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='title_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='title_uz',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
