# Generated by Django 4.1.7 on 2023-04-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_infomodel_location_alter_usersmodel_lang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uz',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
